gridWorkingDir:			workingdirRPARename_20febAliPhysics_pPb
gridOutputDir:			outputdir_13fnew_part2_kEMCEGA_kINT7_kNonLinCorr_latestEMCalCorr
aliPhysicsVersion:		vAN-20220220_ROOT6-1
#aliPhysicsVersion:		vAN-20201205_ROOT6-1
package:			fastjet::v3.2.1_1.024-alice3-94
package:			boost::v1.72.0-alice2-7
#trackCutsPeriod:		lhc13f
gridDataDir:			/alice/data/2013/LHC13f
dataPattern:			/pass4/*/AliESDs.root
runPrefix:			000
runNumber:			[196870, 196874, 196876, 197139, 197142, 197143, 197144, 197145, 197147]
#runNumber:			[196870]
#emcalCorrection:		emcal_correction_pPb.yaml
#emcalCorrection:		emcal_correction_nonLin_pPb.yaml
emcalCorrection:		emcal_correction_dataRun1.yaml
emcalGeometryFilename:		geometry_2015.root
emcalLocal2MasterFilename:	EMCALlocal2master.root
splitMaxInputFileNumber:	30.0
isMC:				false
isEmbed:			false